### ISSUE TITLE
Use parcel

### ISSUE THREAD

**Issue by levino** [OutpostHQ/tasty#31]
This is a follow up on https://github.com/parcel-bundler/parcel/issues/8419#issuecomment-1318208498

You do not use parcel in this repo. Please provide a repo or branch / PR that uses `parcel`. Explain what steps / scripts you ran, which output you expected and which output happened instead. I mean: Do you expect me to now migrate your build chain to parcel? Somewhere in this process you probably got stuck and I can only help you this one step forward. So please commit the current WIP and then ping back. Best would be a failing CI test (maybe the build ci step will fail?).

**Comment by shubham-kaushal** [comment]
@levino I've created PR #32 for parcel migration, plz. check.

**Comment by shubham-kaushal** [comment]
#32 #33
